// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using repasoAPI.Data;

#nullable disable

namespace repasoAPI.Data.Migrations
{
    [DbContext(typeof(DbContextEstudiante))]
    [Migration("20250527030206_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("repasoAPI.Models.Estudiante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Estudiantes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6717d93-e98d-4b08-9c18-231c651d2429"),
                            Apellido = "",
                            Correo = "",
                            Direccion = "",
                            FechaNacimiento = new DateTime(1982, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Juan Pérez",
                            Telefono = ""
                        },
                        new
                        {
                            Id = new Guid("f2d8f7e4-62d0-4fbb-a3db-af69c3224584"),
                            Apellido = "",
                            Correo = "",
                            Direccion = "",
                            FechaNacimiento = new DateTime(2020, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ana Gómez",
                            Telefono = ""
                        },
                        new
                        {
                            Id = new Guid("0c48d132-fb36-4732-8874-8dc523b46f57"),
                            Apellido = "",
                            Correo = "",
                            Direccion = "",
                            FechaNacimiento = new DateTime(1999, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Luis Fernández",
                            Telefono = ""
                        },
                        new
                        {
                            Id = new Guid("807ddb1f-2d0a-4ace-b358-6ff177133672"),
                            Apellido = "",
                            Correo = "",
                            Direccion = "",
                            FechaNacimiento = new DateTime(1982, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "María López",
                            Telefono = ""
                        });
                });

            modelBuilder.Entity("repasoAPI.Models.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Materias", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
